# Generated by Django 4.2.30 on 2026-06-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_actual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_maximo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_minimo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(db_column='contraseña', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='inventario',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
