# Generated by Django 4.2.30 on 2026-06-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_actualizacion', models.DateField()),
                ('stock_maximo', models.IntegerField(max_length=11)),
                ('stock_minimo', models.IntegerField(max_length=11)),
                ('cantidad_actual', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('permisos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_rol', models.IntegerField(max_length=11)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
